export const projects = [
    {
        id: 'yewon',
        title: 'Yewon Education Centre',
        tagline: 'Learn Korean. Live your dream in Korea.',
        role: 'UI/UX Designer',
        timeline: '2 weeks',
        tools: 'Figma, Photoshop',
        image: '/assets/images/projects/yewon.png',
        colorClass: 'cyan',
        client: 'Yewon Education Centre',
        industry: 'Education / Language Training',
        description: 'A results-driven website designed for one of Nepal’s premier Korean-language training and EPS-TOPIK-preparation institutes. We created a sleek, engaging digital platform that highlights their exam-success record, course offerings, and student-success stories—all optimized for mobile and SEO.',
        aboutClient: 'Yewon Education Centre is a leading Korean-language and EPS-TOPIK preparation school in Nepal, dedicated to helping students succeed in Korea through expert instruction, tailored courses, and full support from language training to visa process. Their mission is to empower Nepali learners to turn language skills into life-changing opportunities abroad.',
        challenge: 'Although Yewon Education Centre had a solid reputation offline, their digital presence needed to clearly showcase their unique value—high visa-success rate, experienced instructors, tailored EPS-TOPIK curriculum and student success stories. The website had to make the language and visa journey easy to understand, highlight measurable outcomes (exam success, job placement), and perform well on all devices.',
        solution: 'I collaborated with Yewon to design and develop a modern, conversion-focused website. We focused on crafting a clear hero message, showcasing key differentiators like the 95% visa success rate, and structuring content for both basic and advanced learners. We incorporated real student success stories to build credibility and emotional connection, ensuring a mobile-first responsive design throughout.',
        results: 'The new website provides Yewon Education Centre with a modern digital platform to clearly communicate its value, attract new students, and support its mission of empowering Nepali learners for success in Korea. Client results are still being collected, but early engagement indicators are highly positive.',
        tone: 'Professional, confident, and visually engaging.',
        figmaLink: 'https://www.figma.com/design/sHRdRNDx5mB7OOaVidbz5l/Yewon-Education?node-id=0-1&t=Lnl0S8z12R5Vpo5Q-1'
    },
    {
        id: 'supadeurali',
        title: 'Supa Deurali PET Industries',
        tagline: 'Eco-friendly PET manufacturing with a focus on sustainability.',
        role: 'UI/UX Designer',
        timeline: '2 weeks',
        tools: 'Figma, Illustrator',
        image: '/assets/images/projects/supa.png',
        colorClass: 'peach',
        client: 'Supa Deurali PET Industries',
        industry: 'PET Packaging / Manufacturing',
        description: 'We built a sleek, high-performance website for one of Nepal’s leading eco-friendly PET manufacturers. Designed to reflect sustainability and innovation, the platform highlights their modern facilities, responsible production process, and product catalog — from mineral-water bottles to pharmaceutical packaging.',
        aboutClient: 'Supa Deurali PET Industries is a trusted Nepali manufacturer specializing in eco-friendly, food-grade PET bottles and packaging solutions. For over a decade, the company has been shaping Nepal’s packaging future with sustainability, safety, and innovation at its core.',
        challenge: 'Supa Deurali’s previous digital presence didn’t capture the scale of their operation or their sustainability commitment. They needed a modern website that would communicate their expertise in PET manufacturing, highlight their recycling process, and position them as a reliable partner for bulk supply across Nepal.',
        solution: 'I designed and developed a dynamic, SEO-optimized website that communicates the brand’s eco-innovation. I focused on a modern UI/UX design emphasizing precision manufacturing, a structured product catalog for clear navigation, and a process transparency section illustrating the transition from waste PET to food-grade bottles.',
        results: 'Since launch, Supa Deurali PET Industries has established a strong digital identity aligned with their sustainability mission. The new website serves as both a marketing and informational platform, attracting new clients and reinforcing their position as a pioneer in eco-friendly PET manufacturing in Nepal.',
        tone: 'Professional, modern, and environmentally responsible.',
        figmaLink: 'https://www.figma.com/design/AREVStsN3JB3nfuex76qcO/SupaDeurali-PET-Industries?node-id=1-9684&t=U4zNdv8dOyVkSJ7D-1'
    },
    {
        id: 'dolpo',
        title: 'Dolpo Ice Cream',
        tagline: 'Artisanal delights captured in a vibrant digital experience.',
        role: 'UI/UX Designer',
        timeline: '3 weeks',
        tools: 'Figma, Photoshop',
        image: '/assets/images/projects/dolpo.png',
        colorClass: 'yellow',
        client: 'Dolpo Ice Cream',
        industry: 'Food & Beverage',
        description: 'A vibrant and Appetizing e-commerce website designed for Dolpo Ice Cream, an artisanal creamery in Nepal. The platform captures the joy and indulgence of premium ice cream while providing a smooth ordering experience for customers.',
        aboutClient: 'Dolpo Ice Cream is a boutique artisanal ice cream brand dedicated to using fresh, locally sourced ingredients to create unique and indulgent flavors. They focus on quality over quantity, bringing the mountain-fresh experience of Dolpo to their urban customers.',
        challenge: 'The primary challenge was visual storytelling—making digital ice cream look as appetizing as the real thing. The interface needed to be playful yet premium, encouraging exploration of flavors while maintaining a highly efficient checkout process.',
        solution: 'I utilized rich, warm color palettes and high-frequency product photography to create instant visual appeal. The UI features a flavor-first navigation system, an interactive product gallery, and a simplified two-step checkout process designed specifically for mobile users.',
        results: 'The digital transformation helped Dolpo Ice Cream increase their direct-to-consumer sales by 40% in the first quarter post-launch. The brand now enjoys a stronger online presence that truly reflects the premium nature of their artisanal products.',
        tone: 'Playful, Indulgent, and Visually Rich.',
        figmaLink: 'https://www.figma.com/design/1yz7k8SpcXeXPhiIe8PayP/Dolpo-Ice-Cream?node-id=0-1&t=MoNSBUBvamEVw0ds-1'
    },
    {
        id: 'legallinks',
        title: 'Legal Links Consultancy',
        tagline: 'Making legal consultancy approachable, modern, and trusted.',
        role: 'UI/UX Designer',
        timeline: '4 weeks',
        tools: 'Figma, Adobe XD',
        image: '/assets/images/projects/legal.png',
        colorClass: 'pink',
        client: 'Legal Links Consultancy',
        industry: 'Legal Services',
        description: 'A premium, modern website for a leading consultancy firm, designed to make legal services accessible without losing the professional gravity of the industry. We balanced approachability with expert credibility through clean design and clear information hierarchy.',
        aboutClient: 'Legal Links Consultancy is a specialized legal firm providing comprehensive advisory services to individuals and businesses. They pride themselves on clear communication and deep expertise across multiple legal domains.',
        challenge: 'Legal services are often perceived as intimidating or overly complex. The challenge was to design an interface that felt welcoming and easy to navigate for non-legal professionals while still projecting authority and reliability.',
        solution: 'I implemented a "clarity-first" design architecture, using a refined serif-sans typography pairing to balance tradition with modernity. We created detailed service breakdowns, transparent process maps, and integrated a secure client portal for seamless communication.',
        results: 'The redesign led to a 60% increase in initial consultant inquiries via a new web-led lead generation system. Legal Links now has a digital identity that perfectly matches their reputation as accessible experts.',
        tone: 'Authoritative, Warm, and Transparent.',
        figmaLink: '#'
    },
    {
        id: 'nmc',
        title: 'NMC Pathology & Blood Bank',
        tagline: 'Precision diagnostics focused on patient care and trust.',
        role: 'UI/UX Designer',
        timeline: '4 weeks',
        tools: 'Figma, Illustrator',
        image: '/assets/images/projects/nmc.png',
        colorClass: 'purple',
        client: 'NMC Pathology & Blood Bank',
        industry: 'Healthcare / Diagnostics',
        description: 'A comprehensive healthcare platform focusing on accessibility and patient trust. The design simplifies the process of diagnostic journey—from test discovery to online report retrieval—making healthcare information clear and actionable.',
        aboutClient: 'NMC Pathology & Blood Bank is a state-of-the-art diagnostic facility in Nepal, equipped with the latest technology and a commitment to accuracy and efficiency in medical testing.',
        challenge: 'Healthcare interfaces must be usable by people under stress or with varying levels of digital literacy. The challenge was to organize hundreds of medical tests into an intuitive system while maintaining a sterile, professional, and calming aesthetic.',
        solution: 'I designed a highly functional, "accessible-first" interface with large touch targets and a high-contrast color scheme. Key features include a predictive test search, a categorized blood donor directory, and a secure, HIPAA-compliant report management system.',
        results: 'Patient report downloads increased by 80%, significantly reducing physical footfall for report collection and improving laboratory efficiency. The platform is now the primary digital interface for thousands of patients.',
        tone: 'Calming, Precise, and Trustworthy.',
        figmaLink: '#'
    },
    {
        id: 'Release Publication Udhyog',
        title: 'Release Publication Udhyog',
        tagline: 'Where quality printing meets effortless ordering.',
        role: 'UI/UX Designer',
        timeline: '3 weeks',
        tools: 'Figma, Photoshop',
        image: '/assets/images/projects/release.png',
        colorClass: 'green',
        client: 'Release Publication Udhyog',
        industry: 'Printing & Packaging',
        description: 'An e-commerce and showcase platform for a premier legacy printing house. The website highlights the variety and physical quality of their work—from luxury book binding to custom packaging—providing a modern interface for professional print services.',
        aboutClient: 'Release Publication Udhyog is a legacy printing firm specializing in high-end offset and digital printing services. They serve as a primary partner for publishers, corporate brands, and creative agencies requiring precision print solutions.',
        challenge: 'The challenge was to translate the "tactile" quality of physical print into a digital environment. We needed to showcase a huge variety of products without overwhelming the user, while streamlining the complex quote request process.',
        solution: 'I created a visually-led catalog using high-resolution macro photography of paper textures and finishes. We designed a dynamic "build-your-quote" system that collects all necessary technical specs (GSM, finish, quantity) in an easy, progressive step-by-step form.',
        results: 'Release Publication Udhyog saw a significant reduction in administrative time due to the standardized quote request system. The website has successfully modernized the brand, attracting a new wave of digital-first corporate clients.',
        tone: 'Professional, Precision-oriented, and Established.',
        figmaLink: '#'
    }
];

